version: "3.9"
services:
  ledger:
    # TODO: this image should be one built under the Anoma GitHub organization
    # this image must have `anomac utils fetch-wasms` functionality
    image: ghcr.io/james-chf/devchain-container:sha-8e60590
    platform: linux/amd64
    ports:
      - '127.0.0.1:8123:8123'
      - '127.0.0.1:26657:26657'
  adhoc:
    build: .
    platform: linux/amd64
    environment:
      &anoma_env
      ANOMA_CHAIN_ID: dev.ceed9aae366955c0818d57a280 # ANOMA_CHAIN_ID should match chain ID used in ledger image
      ANOMA_NETWORK_CONFIGS_SERVER: http://ledger:8123
      ANOMA_LEDGER_ADDRESS: ledger:26657
    command:
      - /bin/bash
      - -c
      - |
        tail -F /dev/null
    depends_on:
      - ledger
  testrunner:
    build: .
    platform: linux/amd64
    environment: *anoma_env
    command:
      - /bin/bash
      - -c
      - |
        tests/consecutive_mints && \
        tests/mint_then_burn
    depends_on:
      - ledger
