[package]
name = "shared"
authors = ["Heliax <hello@heliax.dev>"]
license = "GPL-3.0"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
anoma_tx_prelude = {git = "https://github.com/anoma/anoma"}
borsh = "0.9.0"
serde = {version = "1.0.125", features = ["derive"]}